// ─────────────────────────────────────────────────────────────────────────────
// MATYAG — Fictional Political Dataset (Demo / Hackathon Use Only)
// All names, data, and records are entirely fictional.
// ─────────────────────────────────────────────────────────────────────────────

export type Position = 'President' | 'Vice President' | 'Senator' | 'Party-list';
export type Party = 'BPC' | 'DP' | 'LM' | 'KP' | 'IND';
export type FlagStatus = 'clear' | 'pending' | 'dismissed';

export interface AccountabilityFlag {
  status: FlagStatus;
  count: number;
  details: string[];
}

export interface NotableVote {
  bill: string;
  vote: 'YES' | 'NO' | 'ABSTAIN';
}

export interface Politician {
  id: string;
  position: Position;
  ballotNumber?: number;
  honorific: string;
  firstName: string;
  lastName: string;
  nickname?: string;
  fullName: string;                 // computed for display
  party: Party;
  age: number;
  region: string;
  termExperienceYears: number;
  netWorthSALN: number;             // in PHP
  netWorthLabel: string;            // e.g. "₱38.4M"
  salnYear: string;
  billsAuthored: number;
  lawsPassed: number;
  attendanceRate: number;           // percentage 0–100
  attendanceSessions?: string;      // e.g. "124 of 126"
  accountabilityFlags: AccountabilityFlag;
  platform: string[];
  notableVotes?: NotableVote[];
  bio: string;
  profileSrc: number | null;               // path to profile image in assets folder
  // Party-list specific
  organization?: string;
  sector?: string;
}

// ─── PARTY LABELS ────────────────────────────────────────────────────────────
export const PARTIES: Record<Party, string> = {
  BPC: 'Bagong Pilipinas Coalition',
  DP: 'Demokratikong Pagbabago',
  LM: 'Laban ng Mamamayan',
  KP: 'Kilusan Progresibo',
  IND: 'Independent',
};

// ─── PRESIDENTIAL CANDIDATES ─────────────────────────────────────────────────
export const presidents: Politician[] = [
  {
    id: 'p-001',
    position: 'President',
    ballotNumber: 1,
    honorific: 'Hon.',
    firstName: 'Ricardo',
    lastName: 'Montemayor',
    nickname: 'Ricky',
    fullName: 'Ricardo "Ricky" Montemayor',
    party: 'BPC',
    age: 58,
    region: 'Ilocos Norte',
    termExperienceYears: 12,
    netWorthSALN: 38400000,
    netWorthLabel: '₱38.4M',
    salnYear: '2023 Filing',
    billsAuthored: 47,
    lawsPassed: 12,
    attendanceRate: 91,
    accountabilityFlags: {
      status: 'pending',
      count: 2,
      details: [
        'COA disallowance — ₱12M infrastructure fund irregularity',
        'Ombudsman complaint — overpriced medical supplies procurement',
      ],
    },
    platform: ['Infrastructure', 'National Security', 'Anti-Corruption'],
    notableVotes: [
      {bill: 'Renewable Energy Act', vote: 'YES'},
      {bill: 'Freedom of Information Bill', vote: 'NO'},
    ],
    bio: 'Former Governor and Senator from Ilocos Norte. Known for large-scale infrastructure projects and a firm stance on national security. Faces two pending accountability cases.',
    profileSrc: require('../assets/images/president/Ricardo.png'),
  },
  {
    id: 'p-002',
    position: 'President',
    ballotNumber: 2,
    honorific: 'Hon.',
    firstName: 'Esperanza',
    lastName: 'Villanueva-Santos',
    nickname: 'Espe',
    fullName: 'Esperanza "Espe" Villanueva-Santos',
    party: 'DP',
    age: 52,
    region: 'Cebu',
    termExperienceYears: 9,
    netWorthSALN: 21700000,
    netWorthLabel: '₱21.7M',
    salnYear: '2023 Filing',
    billsAuthored: 63,
    lawsPassed: 18,
    attendanceRate: 97,
    accountabilityFlags: {
      status: 'clear',
      count: 0,
      details: [],
    },
    platform: ['Universal Healthcare', 'Education Reform', "Womens Rights"],
    notableVotes: [
      {bill: 'Universal Healthcare Act', vote: 'YES'},
      {bill: 'Anti-Dynasty Bill', vote: 'YES'},
    ],
    bio: 'Former Congresswoman and DILG Undersecretary from Cebu. Champion of healthcare reform and gender equality legislation. Clean accountability record with one of the highest attendance rates among presidential candidates.',
    profileSrc: null,
  },
  {
    id: 'p-003',
    position: 'President',
    ballotNumber: 3,
    honorific: 'Hon.',
    firstName: 'Aurelio',
    lastName: 'Cabanero',
    nickname: 'Dodong',
    fullName: 'Aurelio "Dodong" Cabanero III',
    party: 'LM',
    age: 61,
    region: 'Davao del Sur',
    termExperienceYears: 18,
    netWorthSALN: 74100000,
    netWorthLabel: '₱74.1M',
    salnYear: '2023 Filing',
    billsAuthored: 89,
    lawsPassed: 24,
    attendanceRate: 84,
    accountabilityFlags: {
      status: 'pending',
      count: 2,
      details: [
        'Sandiganbayan case — regional development fund irregularity (dismissed 2019)',
        'Ombudsman probe — road contract anomaly (pending)',
      ],
    },
    platform: ['Law & Order', 'Federalism', 'Agriculture'],
    notableVotes: [
      {bill: 'Death Penalty Restoration Bill', vote: 'YES'},
      {bill: 'SOGIE Equality Bill', vote: 'NO'},
    ],
    bio: 'Three-term former Mayor and Senate President from Davao del Sur. The most experienced candidate by years in office. Commands strong regional support but carries unresolved accountability questions.',
    profileSrc: null,
  },
  {
    id: 'p-004',
    position: 'President',
    ballotNumber: 4,
    honorific: 'Hon.',
    firstName: 'Lorenzo',
    lastName: 'Bautista-Reyes',
    nickname: 'Enzo',
    fullName: 'Lorenzo "Enzo" Bautista-Reyes',
    party: 'KP',
    age: 46,
    region: 'Makati, Metro Manila',
    termExperienceYears: 6,
    netWorthSALN: 312000000,
    netWorthLabel: '₱312M',
    salnYear: '2023 Filing',
    billsAuthored: 28,
    lawsPassed: 4,
    attendanceRate: 88,
    accountabilityFlags: {
      status: 'clear',
      count: 0,
      details: [],
    },
    platform: ['Digital Economy', 'Anti-Poverty', 'Judicial Reform'],
    notableVotes: [
      {bill: 'Open Data Bill', vote: 'YES'},
      {bill: 'Freedom of Information Bill', vote: 'YES'},
    ],
    bio: 'Former tech entrepreneur turned first-time Senator from Makati. Youngest presidential candidate with the highest net worth. Limited legislative track record but a strong transparency and digital reform agenda.',
    profileSrc: null,
  },
];

// ─── VICE PRESIDENTIAL CANDIDATES ────────────────────────────────────────────
export const vicePresidents: Politician[] = [
  {
    id: 'vp-001',
    position: 'Vice President',
    ballotNumber: 1,
    honorific: 'Hon.',
    firstName: 'Corazon',
    lastName: 'Dimaculangan',
    nickname: 'Cora',
    fullName: 'Corazon "Cora" Dimaculangan',
    party: 'BPC',
    age: 54,
    region: 'Pampanga',
    termExperienceYears: 12,
    netWorthSALN: 29300000,
    netWorthLabel: '₱29.3M',
    salnYear: '2023 Filing',
    billsAuthored: 71,
    lawsPassed: 19,
    attendanceRate: 96,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Social Services', 'OFW Affairs', 'Housing'],
    notableVotes: [
      {bill: 'OFW Protection Act', vote: 'YES'},
      {bill: 'Socialized Housing Fund Bill', vote: 'YES'},
    ],
    bio: 'Former Senate Majority Leader and 3-term Senator from Pampanga. Running mate of Montemayor. Regarded as a steady legislative hand with a focus on overseas Filipino workers and housing.',
    profileSrc: null,
  },
  {
    id: 'vp-002',
    position: 'Vice President',
    ballotNumber: 2,
    honorific: 'Hon.',
    firstName: 'Gregorio',
    lastName: 'Padua-Lim',
    nickname: 'Greg',
    fullName: 'Gregorio "Greg" Padua-Lim',
    party: 'DP',
    age: 49,
    region: 'Laguna',
    termExperienceYears: 8,
    netWorthSALN: 11200000,
    netWorthLabel: '₱11.2M',
    salnYear: '2023 Filing',
    billsAuthored: 34,
    lawsPassed: 9,
    attendanceRate: 99,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Fiscal Transparency', 'Anti-Corruption', 'Good Governance'],
    notableVotes: [
      {bill: 'Budget Transparency Act', vote: 'YES'},
      {bill: 'Anti-Red Tape Act Amendment', vote: 'YES'},
    ],
    bio: 'Former COA Commissioner and anti-corruption advocate from Laguna. Running mate of Villanueva-Santos. Lowest net worth among VP candidates — often cited as a point of credibility on his fiscal transparency platform.',
    profileSrc: null,
  },
  {
    id: 'vp-003',
    position: 'Vice President',
    ballotNumber: 3,
    honorific: 'Hon.',
    firstName: 'Maricel',
    lastName: 'Tungol-Adriano',
    nickname: 'MC',
    fullName: 'Maricel "MC" Tungol-Adriano',
    party: 'LM',
    age: 44,
    region: 'Leyte',
    termExperienceYears: 8,
    netWorthSALN: 18900000,
    netWorthLabel: '₱18.9M',
    salnYear: '2023 Filing',
    billsAuthored: 41,
    lawsPassed: 11,
    attendanceRate: 93,
    accountabilityFlags: {
      status: 'pending',
      count: 1,
      details: ['COA flagged ₱4.2M calamity fund usage discrepancy'],
    },
    platform: ['Disaster Resilience', 'Rural Development', 'Environment'],
    notableVotes: [
      {bill: 'Climate Adaptation Fund Bill', vote: 'YES'},
      {bill: 'National Land Use Act', vote: 'YES'},
    ],
    bio: 'Two-term former Governor of Leyte and disaster risk reduction advocate. Running mate of Cabanero. Strong grassroots support in Eastern Visayas. One pending COA flag on calamity fund usage.',
    profileSrc: null,
  },
  {
    id: 'vp-004',
    position: 'Vice President',
    ballotNumber: 4,
    honorific: 'Hon.',
    firstName: 'Fernan',
    lastName: 'Delgado-Cruz',
    nickname: '',
    fullName: 'Fernan Delgado-Cruz',
    party: 'KP',
    age: 38,
    region: 'Batangas',
    termExperienceYears: 4,
    netWorthSALN: 45600000,
    netWorthLabel: '₱45.6M',
    salnYear: '2023 Filing',
    billsAuthored: 19,
    lawsPassed: 3,
    attendanceRate: 90,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Digital Infrastructure', 'Youth Employment', 'Innovation'],
    notableVotes: [
      {bill: 'National Broadband Plan Bill', vote: 'YES'},
      {bill: 'Digital Jobs Act', vote: 'YES'},
    ],
    bio: 'Former DICT Secretary and startup ecosystem builder from Batangas. Running mate of Bautista-Reyes. Youngest VP candidate. Limited electoral experience but regarded as a competent technocrat.',
    profileSrc: null,
  },
];

// ─── SENATORS ─────────────────────────────────────────────────────────────────
export const senators: Politician[] = [
  {
    id: 's-001',
    position: 'Senator',
    ballotNumber: 1,
    honorific: 'Sen.',
    firstName: 'Andres',
    lastName: 'Macaraeg',
    fullName: 'Andres Macaraeg',
    party: 'BPC',
    age: 63,
    region: 'Ilocos Sur',
    termExperienceYears: 18,
    netWorthSALN: 52100000,
    netWorthLabel: '₱52.1M',
    salnYear: '2023 Filing',
    billsAuthored: 102,
    lawsPassed: 31,
    attendanceRate: 88,
    accountabilityFlags: {
      status: 'pending',
      count: 2,
      details: [
        'Ombudsman graft case — irregular awarding of regional contracts',
        'COA disallowance — ₱7.4M public works fund',
      ],
    },
    platform: ['Agrarian Reform', 'Anti-Federalism', 'Rural Infrastructure'],
    notableVotes: [
      {bill: 'Federalism Charter Change Bill', vote: 'NO'},
      {bill: 'Agrarian Reform Extension Act', vote: 'YES'},
    ],
    bio: 'Veteran senator from Ilocos Sur with 18 years of service. Strong agrarian reform advocate. Two pending accountability cases raise questions about fund management.',
    profileSrc: null,
  },
  {
    id: 's-002',
    position: 'Senator',
    ballotNumber: 2,
    honorific: 'Sen.',
    firstName: 'Soledad',
    lastName: 'Ramos-Ferrer',
    nickname: 'Sol',
    fullName: 'Soledad "Sol" Ramos-Ferrer',
    party: 'DP',
    age: 50,
    region: 'Quezon City',
    termExperienceYears: 9,
    netWorthSALN: 14300000,
    netWorthLabel: '₱14.3M',
    salnYear: '2023 Filing',
    billsAuthored: 78,
    lawsPassed: 22,
    attendanceRate: 98,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['SOGIE Rights', 'Mental Health', 'Gender Equality'],
    notableVotes: [
      {bill: 'SOGIE Equality Bill', vote: 'YES'},
      {bill: 'Mental Health Act Amendment', vote: 'YES'},
    ],
    bio: 'Two-term senator from Quezon City. Consistent champion of SOGIE rights and mental health legislation. Near-perfect attendance record and a clean accountability history.',
    profileSrc: null,
  },
  {
    id: 's-003',
    position: 'Senator',
    ballotNumber: 3,
    honorific: 'Sen.',
    firstName: 'Bonifacio',
    lastName: 'Ilustre',
    nickname: 'Bong',
    fullName: 'Bonifacio "Bong" Ilustre',
    party: 'LM',
    age: 67,
    region: 'Cebu',
    termExperienceYears: 24,
    netWorthSALN: 88700000,
    netWorthLabel: '₱88.7M',
    salnYear: '2023 Filing',
    billsAuthored: 134,
    lawsPassed: 44,
    attendanceRate: 79,
    accountabilityFlags: {
      status: 'dismissed',
      count: 1,
      details: ['2018 plunder case — acquitted by Sandiganbayan (2021)'],
    },
    platform: ['Federalism', 'Death Penalty', 'Peace & Order'],
    notableVotes: [
      {bill: 'Death Penalty Restoration Bill', vote: 'YES'},
      {bill: 'Federalism Charter Change Bill', vote: 'YES'},
    ],
    bio: 'Most senior senator from Cebu with 24 years in office and the highest legislative output in this cycle. Acquitted of a 2018 plunder case. Attendance rate has declined in recent years.',
    profileSrc: null,
  },
  {
    id: 's-004',
    position: 'Senator',
    ballotNumber: 4,
    honorific: 'Sen.',
    firstName: 'Clarissa',
    lastName: 'Navarro-Tan',
    fullName: 'Clarissa Navarro-Tan',
    party: 'KP',
    age: 41,
    region: 'Taguig',
    termExperienceYears: 3,
    netWorthSALN: 9800000,
    netWorthLabel: '₱9.8M',
    salnYear: '2023 Filing',
    billsAuthored: 31,
    lawsPassed: 6,
    attendanceRate: 96,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Open Data', 'Digital Rights', 'Cybersecurity'],
    notableVotes: [
      {bill: 'Open Data Bill', vote: 'YES'},
      {bill: 'SIM Registration Act', vote: 'NO'},
    ],
    bio: 'First-term senator from Taguig and former tech policy consultant. Strong advocate for digital rights and data privacy. Clean record and above-average attendance for a freshman senator.',
    profileSrc: null,
  },
  {
    id: 's-005',
    position: 'Senator',
    ballotNumber: 5,
    honorific: 'Sen.',
    firstName: 'Herminio',
    lastName: 'Salcedo',
    nickname: 'Minong',
    fullName: 'Herminio "Minong" Salcedo',
    party: 'BPC',
    age: 59,
    region: 'Pampanga',
    termExperienceYears: 12,
    netWorthSALN: 41200000,
    netWorthLabel: '₱41.2M',
    salnYear: '2023 Filing',
    billsAuthored: 88,
    lawsPassed: 19,
    attendanceRate: 91,
    accountabilityFlags: {
      status: 'pending',
      count: 1,
      details: ['PCIJ report: irregular quarry permits in home province (under review)'],
    },
    platform: ['Infrastructure', 'Public-Private Partnership', 'Central Luzon Dev'],
    notableVotes: [
      {bill: 'Build Better More Infrastructure Act', vote: 'YES'},
      {bill: 'Mining Reform Bill', vote: 'NO'},
    ],
    bio: 'Two-term senator from Pampanga focused on infrastructure and PPP initiatives. Flagged in a PCIJ report regarding quarry permits. Still under review with no formal charges filed.',
    profileSrc: null,
  },
  {
    id: 's-006',
    position: 'Senator',
    ballotNumber: 6,
    honorific: 'Sen.',
    firstName: 'Theresa',
    lastName: 'Evangelista',
    nickname: 'Tess',
    fullName: 'Theresa "Tess" Evangelista',
    party: 'IND',
    age: 55,
    region: 'Iloilo',
    termExperienceYears: 9,
    netWorthSALN: 22400000,
    netWorthLabel: '₱22.4M',
    salnYear: '2023 Filing',
    billsAuthored: 65,
    lawsPassed: 21,
    attendanceRate: 97,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Universal Healthcare', 'Hospital Infrastructure', 'PhilHealth Reform'],
    notableVotes: [
      {bill: 'Universal Healthcare Act', vote: 'YES'},
      {bill: 'PhilHealth Reform Bill', vote: 'YES'},
    ],
    bio: 'Independent two-term senator from Iloilo and former physician. One of the most credible voices on healthcare legislation. No party affiliation; widely respected across the aisle.',
    profileSrc: null,
  },
  {
    id: 's-007',
    position: 'Senator',
    ballotNumber: 7,
    honorific: 'Sen.',
    firstName: 'Rodrigo',
    lastName: 'Abad-Santos Jr.',
    nickname: 'Digoy',
    fullName: 'Rodrigo "Digoy" Abad-Santos Jr.',
    party: 'LM',
    age: 62,
    region: 'Davao del Norte',
    termExperienceYears: 15,
    netWorthSALN: 63500000,
    netWorthLabel: '₱63.5M',
    salnYear: '2023 Filing',
    billsAuthored: 97,
    lawsPassed: 27,
    attendanceRate: 85,
    accountabilityFlags: {
      status: 'pending',
      count: 2,
      details: [
        'COA anomaly — ₱8M irregularity in public market project',
        'Ombudsman lifestyle check — asset growth under scrutiny',
      ],
    },
    platform: ['Law & Order', 'AFP Modernization', 'Mindanao Security'],
    notableVotes: [
      {bill: 'AFP Modernization Act Extension', vote: 'YES'},
      {bill: 'Human Rights Commission Budget', vote: 'NO'},
    ],
    bio: 'Veteran senator from Davao del Norte with a strong law-and-order platform. Two pending accountability cases, including a lifestyle check flagged by the Ombudsman.',
    profileSrc: null,
  },
  {
    id: 's-008',
    position: 'Senator',
    ballotNumber: 8,
    honorific: 'Sen.',
    firstName: 'Patricia',
    lastName: 'Ocampo-Reyes',
    nickname: 'Pat',
    fullName: 'Patricia "Pat" Ocampo-Reyes',
    party: 'DP',
    age: 47,
    region: 'Batangas',
    termExperienceYears: 6,
    netWorthSALN: 17600000,
    netWorthLabel: '₱17.6M',
    salnYear: '2023 Filing',
    billsAuthored: 54,
    lawsPassed: 14,
    attendanceRate: 99,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ["Womens Rights", 'Labor Protection', 'Anti-VAWC'],
    notableVotes: [
      {bill: 'Safe Spaces Act', vote: 'YES'},
      {bill: 'Labor Code Amendment', vote: 'YES'},
    ],
    bio: 'Second-term senator from Batangas and former labor lawyer. Highest attendance rate in the Senate this cycle (99%). Authored landmark amendments to the Anti-VAWC Act.',
    profileSrc: null,
  },
  {
    id: 's-009',
    position: 'Senator',
    ballotNumber: 9,
    honorific: 'Sen.',
    firstName: 'Victorino',
    lastName: 'Gaston',
    nickname: 'Vic',
    fullName: 'Victorino "Vic" Gaston',
    party: 'BPC',
    age: 70,
    region: 'Negros Occidental',
    termExperienceYears: 21,
    netWorthSALN: 97300000,
    netWorthLabel: '₱97.3M',
    salnYear: '2023 Filing',
    billsAuthored: 119,
    lawsPassed: 38,
    attendanceRate: 74,
    accountabilityFlags: {
      status: 'pending',
      count: 3,
      details: [
        'Ombudsman lifestyle check — significant unexplained asset growth',
        'Sugar quota anomaly — congressional inquiry ongoing',
        'Sandiganbayan case — pending, malversation of public funds',
      ],
    },
    platform: ['Agriculture', 'Sugar Industry', 'Negros Development'],
    notableVotes: [
      {bill: 'Sugar Industry Development Act', vote: 'YES'},
      {bill: 'Anti-Political Dynasty Bill', vote: 'NO'},
    ],
    bio: 'Longest-serving active senator from Negros Occidental. Highest net worth and most accountability flags in this cycle. Strong agricultural bloc backing despite ongoing legal challenges.',
    profileSrc: null,
  },
  {
    id: 's-010',
    position: 'Senator',
    ballotNumber: 10,
    honorific: 'Sen.',
    firstName: 'Marisol',
    lastName: 'Cabrera-Lim',
    fullName: 'Marisol Cabrera-Lim',
    party: 'KP',
    age: 39,
    region: 'Makati',
    termExperienceYears: 3,
    netWorthSALN: 8100000,
    netWorthLabel: '₱8.1M',
    salnYear: '2023 Filing',
    billsAuthored: 27,
    lawsPassed: 3,
    attendanceRate: 94,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Startup Ecosystem', 'Anti-Poverty Tech', 'Digital Finance'],
    notableVotes: [
      {bill: 'Fintech Regulatory Sandbox Act', vote: 'YES'},
      {bill: 'Digital Peso Bill', vote: 'YES'},
    ],
    bio: 'First-term senator from Makati and former fintech executive. Youngest sitting senator. Focused on leveraging technology for poverty reduction and financial inclusion.',
    profileSrc: null,
  },
  {
    id: 's-011',
    position: 'Senator',
    ballotNumber: 11,
    honorific: 'Sen.',
    firstName: 'Emmanuel',
    lastName: 'Florido',
    nickname: 'Manny',
    fullName: 'Emmanuel "Manny" Florido',
    party: 'LM',
    age: 56,
    region: 'Maguindanao',
    termExperienceYears: 9,
    netWorthSALN: 33900000,
    netWorthLabel: '₱33.9M',
    salnYear: '2023 Filing',
    billsAuthored: 73,
    lawsPassed: 18,
    attendanceRate: 87,
    accountabilityFlags: {
      status: 'dismissed',
      count: 1,
      details: ['2020 EJK allegation — case dismissed for lack of evidence (2022)'],
    },
    platform: ['Mindanao Peace', 'MILF Accord', 'Muslim Mindanao Autonomy'],
    notableVotes: [
      {bill: 'Bangsamoro Organic Law', vote: 'YES'},
      {bill: 'Anti-Terror Act', vote: 'YES'},
    ],
    bio: 'Two-term senator from Maguindanao and key peace process negotiator. A 2020 extrajudicial killing allegation was dismissed in 2022. Remains the leading voice for Mindanao autonomy in the Senate.',
    profileSrc: null,
  },
  {
    id: 's-012',
    position: 'Senator',
    ballotNumber: 12,
    honorific: 'Sen.',
    firstName: 'Jovita',
    lastName: 'Delos Santos',
    nickname: 'Joy',
    fullName: 'Jovita "Joy" Delos Santos',
    party: 'IND',
    age: 44,
    region: 'Leyte',
    termExperienceYears: 6,
    netWorthSALN: 12700000,
    netWorthLabel: '₱12.7M',
    salnYear: '2023 Filing',
    billsAuthored: 48,
    lawsPassed: 11,
    attendanceRate: 96,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Disaster Resilience', 'Climate Adaptation', 'Coastal Protection'],
    notableVotes: [
      {bill: 'Climate Change Act Amendment', vote: 'YES'},
      {bill: 'National Disaster Risk Reduction Fund', vote: 'YES'},
    ],
    bio: 'Independent second-term senator from typhoon-prone Leyte. Personal experience with Yolanda drives her disaster resilience platform. One of the most consistently rated senators by civil society groups.',
    profileSrc: null,
  },
  {
    id: 's-013',
    position: 'Senator',
    ballotNumber: 13,
    honorific: 'Sen.',
    firstName: 'Carlos',
    lastName: 'Aquino-Mendez',
    fullName: 'Carlos Aquino-Mendez',
    party: 'DP',
    age: 52,
    region: 'Pangasinan',
    termExperienceYears: 9,
    netWorthSALN: 25200000,
    netWorthLabel: '₱25.2M',
    salnYear: '2023 Filing',
    billsAuthored: 61,
    lawsPassed: 17,
    attendanceRate: 93,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Education', "Teachers' Welfare", 'State Universities'],
    notableVotes: [
      {bill: "Teachers' Salary Standardization Act", vote: 'YES'},
      {bill: 'SUC Budget Increase', vote: 'YES'},
    ],
    bio: 'Two-term senator from Pangasinan and former DepEd Undersecretary. Consistent advocate for public school teachers and state university funding. Clean record, reliable workhorse legislator.',
    profileSrc: null,
  },
  {
    id: 's-014',
    position: 'Senator',
    ballotNumber: 14,
    honorific: 'Sen.',
    firstName: 'Rosario',
    lastName: 'Buenaventura',
    nickname: 'Charo',
    fullName: 'Rosario "Charo" Buenaventura',
    party: 'BPC',
    age: 65,
    region: 'Zamboanga',
    termExperienceYears: 18,
    netWorthSALN: 71400000,
    netWorthLabel: '₱71.4M',
    salnYear: '2023 Filing',
    billsAuthored: 108,
    lawsPassed: 33,
    attendanceRate: 82,
    accountabilityFlags: {
      status: 'pending',
      count: 1,
      details: ['PCIJ report: relatives awarded government contracts in Zamboanga region'],
    },
    platform: ['National Defense', 'Mindanao Development', 'Anti-Terrorism'],
    notableVotes: [
      {bill: 'Anti-Terror Act', vote: 'YES'},
      {bill: 'Anti-Political Dynasty Bill', vote: 'NO'},
    ],
    bio: 'Veteran senator from Zamboanga with 18 years in office. Influential on defense and Mindanao policy. A PCIJ investigation into family members benefiting from government contracts is currently under review.',
    profileSrc: null,
  },
  {
    id: 's-015',
    position: 'Senator',
    ballotNumber: 15,
    honorific: 'Sen.',
    firstName: 'Arnulfo',
    lastName: 'Tiongson',
    nickname: 'Jun',
    fullName: 'Arnulfo "Jun" Tiongson',
    party: 'KP',
    age: 43,
    region: 'Laguna',
    termExperienceYears: 3,
    netWorthSALN: 6400000,
    netWorthLabel: '₱6.4M',
    salnYear: '2023 Filing',
    billsAuthored: 22,
    lawsPassed: 2,
    attendanceRate: 91,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Tax Reform', 'SME Support', 'MSME Digitization'],
    notableVotes: [
      {bill: 'MSME Credit Access Act', vote: 'YES'},
      {bill: 'Corporate Tax Reform Bill', vote: 'YES'},
    ],
    bio: 'First-term senator from Laguna and former MSME advocate. Lowest net worth among senators — a point of pride on his campaign trail. Limited track record but focused legislative agenda.',
    profileSrc: null,
  },
  {
    id: 's-016',
    position: 'Senator',
    ballotNumber: 16,
    honorific: 'Sen.',
    firstName: 'Natividad',
    lastName: 'Vergara',
    nickname: 'Naty',
    fullName: 'Natividad "Naty" Vergara',
    party: 'LM',
    age: 61,
    region: 'Samar',
    termExperienceYears: 12,
    netWorthSALN: 38600000,
    netWorthLabel: '₱38.6M',
    salnYear: '2023 Filing',
    billsAuthored: 84,
    lawsPassed: 23,
    attendanceRate: 89,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Social Welfare', 'Senior Citizens', '4Ps Expansion'],
    notableVotes: [
      {bill: 'Expanded Senior Citizens Act', vote: 'YES'},
      {bill: '4Ps Budget Increase', vote: 'YES'},
    ],
    bio: 'Two-term senator from Samar and former DSWD Secretary. Consistent champion of social protection programs. Clean record and strong grassroots support from beneficiary communities.',
    profileSrc: null,
  },
  {
    id: 's-017',
    position: 'Senator',
    ballotNumber: 17,
    honorific: 'Sen.',
    firstName: 'Domingo',
    lastName: 'Espiritu III',
    nickname: 'Doms',
    fullName: 'Domingo "Doms" Espiritu III',
    party: 'BPC',
    age: 58,
    region: 'Rizal',
    termExperienceYears: 12,
    netWorthSALN: 48100000,
    netWorthLabel: '₱48.1M',
    salnYear: '2023 Filing',
    billsAuthored: 91,
    lawsPassed: 26,
    attendanceRate: 86,
    accountabilityFlags: {
      status: 'pending',
      count: 2,
      details: [
        'BIR underdeclaration — SALN inconsistency flagged (under review)',
        'COA overpricing — ₱5.1M in medical equipment procurement',
      ],
    },
    platform: ['National Budget', 'Taxation', 'Fiscal Policy'],
    notableVotes: [
      {bill: 'General Appropriations Act 2024', vote: 'YES'},
      {bill: 'Wealth Tax Bill', vote: 'NO'},
    ],
    bio: 'Two-term senator from Rizal and former Finance Undersecretary. Chair of the Senate Finance Committee. Ironically faces two pending cases related to financial irregularities — a point of criticism from opponents.',
    profileSrc: null,
  },
  {
    id: 's-018',
    position: 'Senator',
    ballotNumber: 18,
    honorific: 'Hon.',
    firstName: 'Leah',
    lastName: 'Gonzales-Abueva',
    fullName: 'Leah Gonzales-Abueva',
    party: 'DP',
    age: 36,
    region: 'Cebu City',
    termExperienceYears: 0,
    netWorthSALN: 4200000,
    netWorthLabel: '₱4.2M',
    salnYear: '2023 Filing',
    billsAuthored: 0,
    lawsPassed: 0,
    attendanceRate: 0,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Youth Empowerment', 'Affordable Housing', 'First-time Voters'],
    notableVotes: [],
    bio: 'First-time senatorial candidate from Cebu City and former youth council president. Youngest candidate in the senatorial race. No legislative record yet but brings strong grassroots youth mobilization.',
    profileSrc: null,
  },
  {
    id: 's-019',
    position: 'Senator',
    ballotNumber: 19,
    honorific: 'Sen.',
    firstName: 'Simplicio',
    lastName: 'Datu-Apao',
    nickname: 'Simpi',
    fullName: 'Simplicio "Simpi" Datu-Apao',
    party: 'IND',
    age: 49,
    region: 'Cagayan de Oro',
    termExperienceYears: 6,
    netWorthSALN: 19800000,
    netWorthLabel: '₱19.8M',
    salnYear: '2023 Filing',
    billsAuthored: 43,
    lawsPassed: 9,
    attendanceRate: 92,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Mindanao Development', 'Indigenous Peoples Rights', 'Northern Mindanao'],
    notableVotes: [
      {bill: 'Indigenous Peoples Rights Act Amendment', vote: 'YES'},
      {bill: 'Mindanao Development Authority Act', vote: 'YES'},
    ],
    bio: 'Independent second-term senator from Cagayan de Oro. Primary voice for indigenous peoples rights and Northern Mindanao development in the Senate. Known for bipartisan cooperation.',
    profileSrc: null,
  },
  {
    id: 's-020',
    position: 'Senator',
    ballotNumber: 20,
    honorific: 'Sen.',
    firstName: 'Felicitas',
    lastName: 'Monsod-Cruz',
    nickname: 'Fely',
    fullName: 'Felicitas "Fely" Monsod-Cruz',
    party: 'KP',
    age: 53,
    region: 'Pasig',
    termExperienceYears: 6,
    netWorthSALN: 23100000,
    netWorthLabel: '₱23.1M',
    salnYear: '2023 Filing',
    billsAuthored: 57,
    lawsPassed: 13,
    attendanceRate: 95,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Environment', 'Renewable Energy', 'Green Infrastructure'],
    notableVotes: [
      {bill: 'Renewable Energy Act Amendment', vote: 'YES'},
      {bill: 'Coal Phase-Out Bill', vote: 'YES'},
    ],
    bio: 'Second-term senator from Pasig and former DENR Undersecretary. Leading environmental voice in the Senate. Authored the landmark Renewable Energy Act amendment passed in 2022.',
    profileSrc: null,
  },
  {
    id: 's-021',
    position: 'Senator',
    ballotNumber: 21,
    honorific: 'Sen.',
    firstName: 'Renato',
    lastName: 'Dimalanta',
    nickname: 'Nato',
    fullName: 'Renato "Nato" Dimalanta',
    party: 'LM',
    age: 64,
    region: 'Ilocos Norte',
    termExperienceYears: 15,
    netWorthSALN: 59800000,
    netWorthLabel: '₱59.8M',
    salnYear: '2023 Filing',
    billsAuthored: 111,
    lawsPassed: 29,
    attendanceRate: 81,
    accountabilityFlags: {
      status: 'dismissed',
      count: 1,
      details: ['2016 election protest — dismissed by HRET (2017)'],
    },
    platform: ['Agrarian Reform', 'NPA Peace Talks', 'Northern Luzon'],
    notableVotes: [
      {bill: 'Comprehensive Agrarian Reform Extension', vote: 'YES'},
      {bill: 'Anti-Terror Act', vote: 'NO'},
    ],
    bio: 'Veteran senator from Ilocos Norte with a peace negotiation background. A 2016 election protest was dismissed. One of few senators to vote against the Anti-Terror Act, citing civil liberties concerns.',
    profileSrc: null,
  },
  {
    id: 's-022',
    position: 'Senator',
    ballotNumber: 22,
    honorific: 'Sen.',
    firstName: 'Carmela',
    lastName: 'Yulo-Macasaet',
    fullName: 'Carmela Yulo-Macasaet',
    party: 'DP',
    age: 40,
    region: 'Taguig',
    termExperienceYears: 3,
    netWorthSALN: 11500000,
    netWorthLabel: '₱11.5M',
    salnYear: '2023 Filing',
    billsAuthored: 33,
    lawsPassed: 5,
    attendanceRate: 97,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['LGBTQ+ Rights', 'Mental Health', 'PWD Inclusion'],
    notableVotes: [
      {bill: 'SOGIE Equality Bill', vote: 'YES'},
      {bill: 'Mental Health Act Amendment', vote: 'YES'},
    ],
    bio: 'First-term senator from Taguig and former PWD rights lawyer. Known for intersectional advocacy combining LGBTQ+, mental health, and disability rights. Strong attendance record.',
    profileSrc: null,
  },
  {
    id: 's-023',
    position: 'Senator',
    ballotNumber: 23,
    honorific: 'Sen.',
    firstName: 'Isidro',
    lastName: 'Arroyo-Perez',
    nickname: 'Sid',
    fullName: 'Isidro "Sid" Arroyo-Perez',
    party: 'BPC',
    age: 57,
    region: 'Cavite',
    termExperienceYears: 9,
    netWorthSALN: 44700000,
    netWorthLabel: '₱44.7M',
    salnYear: '2023 Filing',
    billsAuthored: 76,
    lawsPassed: 20,
    attendanceRate: 88,
    accountabilityFlags: {
      status: 'pending',
      count: 1,
      details: ['Rappler report: anomalous PPP contract awarded to relative&apos;s firm in Cavite (under review)'],
    },
    platform: ['Infrastructure', 'Tourism', 'Cavite-Laguna Development'],
    notableVotes: [
      {bill: 'Tourism Infrastructure Fund Bill', vote: 'YES'},
      {bill: 'Freedom of Information Bill', vote: 'NO'},
    ],
    bio: 'Two-term senator from Cavite focused on infrastructure and tourism. A Rappler report on a PPP contract allegedly awarded to a relative&apos;s firm is currently under review.',
    profileSrc: null,
  },
  {
    id: 's-024',
    position: 'Senator',
    ballotNumber: 24,
    honorific: 'Sen.',
    firstName: 'Marita',
    lastName: 'Rebollos-Ocfemia',
    fullName: 'Marita Rebollos-Ocfemia',
    party: 'IND',
    age: 48,
    region: 'Albay',
    termExperienceYears: 6,
    netWorthSALN: 16300000,
    netWorthLabel: '₱16.3M',
    salnYear: '2023 Filing',
    billsAuthored: 52,
    lawsPassed: 12,
    attendanceRate: 94,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Disaster Preparedness', 'Agriculture', 'Bicol Development'],
    notableVotes: [
      {bill: 'Volcano Hazard Zone Resettlement Act', vote: 'YES'},
      {bill: 'Rice Tariffication Law Amendment', vote: 'YES'},
    ],
    bio: 'Independent second-term senator from Albay — Mayon Volcano country. Personal experience with volcanic evacuations drives her disaster preparedness platform. Respected across party lines.',
    profileSrc: null,
  },
];

// ─── PARTY-LIST REPRESENTATIVES ───────────────────────────────────────────────
export const partyList: Politician[] = [
  {
    id: 'pl-001',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Kristine',
    lastName: 'Malaya',
    fullName: 'Kristine Malaya',
    party: 'KP',
    age: 29,
    region: 'National',
    organization: 'ALAB-Kabataan',
    sector: 'Youth & Students',
    termExperienceYears: 3,
    netWorthSALN: 1800000,
    netWorthLabel: '₱1.8M',
    salnYear: '2023 Filing',
    billsAuthored: 18,
    lawsPassed: 3,
    attendanceRate: 96,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Free Education', 'Youth Employment', 'Student Debt Relief'],
    bio: 'Youngest party-list representative. Former student council national president. Advocates for universal free education and youth entrepreneurship programs.',
    profileSrc: null,
  },
  {
    id: 'pl-002',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Danilo',
    lastName: 'Quiambao',
    fullName: 'Danilo Quiambao',
    party: 'LM',
    age: 54,
    region: 'Central Luzon',
    organization: 'BUHAY Magsasaka',
    sector: 'Farmers & Rural Poor',
    termExperienceYears: 6,
    netWorthSALN: 3200000,
    netWorthLabel: '₱3.2M',
    salnYear: '2023 Filing',
    billsAuthored: 24,
    lawsPassed: 7,
    attendanceRate: 91,
    accountabilityFlags: {
      status: 'pending',
      count: 1,
      details: ['Sector representation dispute — COMELEC review ongoing on org membership legitimacy'],
    },
    platform: ['Land Reform', 'Irrigation', 'Farm-to-Market Roads'],
    bio: 'Second-term party-list representative for farmers from Central Luzon. Faces a COMELEC sector representation review — opponents question whether the org genuinely represents small farmers.',
    profileSrc: null,
  },
  {
    id: 'pl-003',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Rosemarie',
    lastName: 'Tolentino',
    nickname: 'Bing',
    fullName: 'Rosemarie "Bing" Tolentino',
    party: 'DP',
    age: 47,
    region: 'National',
    organization: 'SIKAP Manggagawa',
    sector: 'Labor & Workers',
    termExperienceYears: 6,
    netWorthSALN: 5100000,
    netWorthLabel: '₱5.1M',
    salnYear: '2023 Filing',
    billsAuthored: 31,
    lawsPassed: 9,
    attendanceRate: 98,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Wage Increase', 'Labor Rights', 'End of Contractualization'],
    bio: 'Second-term party-list representative for workers. Former union organizer with 20 years in labor advocacy. Highest attendance rate among party-list reps. Key author of the No-Endo Law amendment.',
    profileSrc: null,
  },
  {
    id: 'pl-004',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Ramonito',
    lastName: 'Dagdagui',
    nickname: 'Ramie',
    fullName: 'Ramonito "Ramie" Dagdagui',
    party: 'IND',
    age: 51,
    region: 'Mindanao',
    organization: 'UGAT ng Bayan',
    sector: 'Indigenous Peoples',
    termExperienceYears: 3,
    netWorthSALN: 2400000,
    netWorthLabel: '₱2.4M',
    salnYear: '2023 Filing',
    billsAuthored: 14,
    lawsPassed: 4,
    attendanceRate: 89,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Ancestral Domain', 'IP Rights', 'Cultural Preservation'],
    bio: 'First-term party-list representative for indigenous peoples from Mindanao. Former NCIP regional director. Advocates for free, prior, and informed consent on all development projects on ancestral land.',
    profileSrc: null,
  },
  {
    id: 'pl-005',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Glenda',
    lastName: 'Corpuz-Ramos',
    fullName: 'Glenda Corpuz-Ramos',
    party: 'KP',
    age: 43,
    region: 'National',
    organization: 'TINDIG PWD',
    sector: 'Persons with Disabilities',
    termExperienceYears: 6,
    netWorthSALN: 3700000,
    netWorthLabel: '₱3.7M',
    salnYear: '2023 Filing',
    billsAuthored: 21,
    lawsPassed: 6,
    attendanceRate: 97,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Accessibility', 'PWD Rights', 'Inclusive Employment'],
    bio: 'Second-term party-list representative for persons with disabilities. Wheelchair user herself. Authored the landmark Mandatory Accessibility Compliance Act. Widely respected across party lines.',
    profileSrc: null,
  },
  {
    id: 'pl-006',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Ernesto',
    lastName: 'Bulan',
    nickname: 'Ernie',
    fullName: 'Ernesto "Ernie" Bulan',
    party: 'IND',
    age: 58,
    region: 'Western Visayas',
    organization: 'DAGAT Pilipinas',
    sector: 'Fisherfolk',
    termExperienceYears: 3,
    netWorthSALN: 2100000,
    netWorthLabel: '₱2.1M',
    salnYear: '2023 Filing',
    billsAuthored: 16,
    lawsPassed: 3,
    attendanceRate: 85,
    accountabilityFlags: {
      status: 'pending',
      count: 1,
      details: ['COA flag — ₱1.8M fisherfolk livelihood fund disbursement irregularity'],
    },
    platform: ['Maritime Rights', 'Fisherfolk Welfare', 'Coral Reef Protection'],
    bio: 'First-term party-list representative for fisherfolk from Western Visayas. Former fisher cooperative head. One pending COA flag on a livelihood fund. Attendance rate slightly below average.',
    profileSrc: null,
  },
  {
    id: 'pl-007',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Sheryl Anne',
    lastName: 'Mirasol',
    fullName: 'Sheryl Anne Mirasol',
    party: 'DP',
    age: 38,
    region: 'National',
    organization: 'BUKAS Kababaihan',
    sector: 'Women',
    termExperienceYears: 3,
    netWorthSALN: 4600000,
    netWorthLabel: '₱4.6M',
    salnYear: '2023 Filing',
    billsAuthored: 27,
    lawsPassed: 8,
    attendanceRate: 99,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Anti-VAWC', "Womens Economic Rights", 'Safe Spaces'],
    bio: 'First-term party-list representative for women with the highest bills-to-laws ratio among party-list reps. Former UN Women consultant. Perfect attendance champion in the House this cycle.',
    profileSrc: null,
  },
  {
    id: 'pl-008',
    position: 'Party-list',
    honorific: 'Rep.',
    firstName: 'Celestino',
    lastName: 'Pascual',
    nickname: 'Lolo Tino',
    fullName: 'Celestino "Lolo Tino" Pascual',
    party: 'BPC',
    age: 72,
    region: 'National',
    organization: 'AGAPAY Senior',
    sector: 'Senior Citizens',
    termExperienceYears: 6,
    netWorthSALN: 7800000,
    netWorthLabel: '₱7.8M',
    salnYear: '2023 Filing',
    billsAuthored: 19,
    lawsPassed: 5,
    attendanceRate: 88,
    accountabilityFlags: {status: 'clear', count: 0, details: []},
    platform: ['Pension Reform', 'Elder Care', 'Senior Healthcare Access'],
    bio: 'Second-term party-list representative for senior citizens and the oldest member of the House this cycle. Former SSS board member. Beloved figure across the aisle for his consistent and collegial approach.',
    profileSrc: null,
  },
];

// ─── COMBINED EXPORT ──────────────────────────────────────────────────────────
export const allPoliticians: Politician[] = [
  ...presidents,
  ...vicePresidents,
  ...senators,
  ...partyList,
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

/** Filter by position */
export const getByPosition = (position: Position): Politician[] =>
  allPoliticians.filter(p => p.position === position);

/** Filter by party */
export const getByParty = (party: Party): Politician[] =>
  allPoliticians.filter(p => p.party === party);

/** Get a single politician by ID */
export const getById = (id: string): Politician | undefined =>
  allPoliticians.find(p => p.id === id);

/** Get politicians with pending accountability flags */
export const getFlagged = (): Politician[] =>
  allPoliticians.filter(p => p.accountabilityFlags.status === 'pending');

/** Search by name (case-insensitive) */
export const searchByName = (query: string): Politician[] => {
  const q = query.toLowerCase();
  return allPoliticians.filter(p => p.fullName.toLowerCase().includes(q));
};